### ISSUE TITLE
introduction description is incorrect

### ISSUE THREAD

**Issue by gasolin** [bitfinexcom/grenache-nodejs-http#25]
Now it says `Grenache Node.JS WebSocket implementation` but actually its `Grenache Node.JS HTTP implementation`

**Comment by robertkowalski** [comment]
thx, seems it was fixed. 

feel free to supply a patch next time, we are all in this boat together.

**Comment by gasolin** [comment]
@robertkowalski I saw the description is still not changed
 ![Imgur](https://i.imgur.com/jcNY7rG.png)

It's not patchable and only can be modified by people with the permission
